import messages from './tag-messages.js';
export default [
//    { tag: 'divider1', intlLabel: 'Actions', type: 'title' }, //??
    { tag: 'custom', intlLabel: messages.customextension, type: 'custom', func: (library) => {
        library.select(''); // selects custom extension since it's id is ''
    } },
	{ tag: 'divider3', intlLabel: messages.scratch, type: 'divider' },
    //{ tag: 'divider1', intlLabel: 'Tags', type: 'title' }, //??
	{type: 'subtitle', intlLabel: "Sources"},
    { tag: 'gaiamod', intlLabel: messages.gaiamod },
    { tag: 'electramod', intlLabel: messages.electramod },
    { tag: 'arkide', intlLabel: messages.arkide },
    { tag: 'snailide', intlLabel: messages.snailide },
    { tag: 'dinosaurmod', intlLabel: messages.dinosaurmod },
    { tag: 'penguinmod', intlLabel: messages.penguinmod },
	{ tag: 'sharkpool', intlLabel: messages.sharkpool },
	{ tag: 'gvbvdxxmod', intlLabel: messages.gvbvdxxmod },
	{ tag: 'adacraft', intlLabel: messages.adacraft },
	{ tag: 'nitrobolt', intlLabel: messages.nitrobolt },
	{ tag: 'acidmod', intlLabel: messages.acidmod },
	{ tag: 'astraeditor', intlLabel: messages.astraeditor },
	{ tag: 'zerotwoengine', intlLabel: messages.zerotwoengine },
	{ tag: 'bilup', intlLabel: messages.bilup },
	{ tag: 'mistwarp', intlLabel: messages.mistwarp },
	{ tag: 'dash', intlLabel: messages.dash },
	{ tag: 'gandiide', intlLabel: messages.gandiide },
    { tag: 'turbowarp', intlLabel: messages.turbowarp },
    { tag: 'scratch', intlLabel: messages.scratch },
	{ tag: 'othermods', intlLabel: messages.othermods },
    { tag: 'divider2', intlLabel: messages.scratch, type: 'divider' },
	{type: 'subtitle', intlLabel: "Types"},
    { tag: 'graphics', intlLabel: messages.graphics },
    { tag: 'noisemaker', intlLabel: messages.noisemaker },
    { tag: 'math', intlLabel: messages.math },
    { tag: 'jokes', intlLabel: messages.jokes },
    { tag: 'datamgmt', intlLabel: messages.datamgmt },
    { tag: 'hardware', intlLabel: messages.hardware },
    { tag: 'ai', intlLabel: messages.ai },
    { tag: 'iot', intlLabel: messages.iot },
    { tag: 'divider2', intlLabel: messages.scratch, type: 'divider' },
	{type: 'subtitle', intlLabel: "Other"},
    { tag: 'categoryexpansion', intlLabel: messages.categoryexpansion },
    { tag: 'programminglanguage', intlLabel: messages.programminglanguage },
    { tag: 'divider1', intlLabel: messages.scratch, type: 'divider' },
    { tag: 'library', intlLabel: messages.library },
    { tag: 'extcreate', intlLabel: messages.extcreate },
    { tag: 'divider2', intlLabel: messages.scratch, type: 'divider' },
	{type: 'subtitle', intlLabel: "Statuses"},
    { tag: 'new', intlLabel: messages.new },
    { tag: 'disabled', intlLabel: messages.disabled },
    { tag: 'comingsoon', intlLabel: messages.comingsoon },
];
