/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "name": "Automatically add extensions",
  "description": "Auto-shows music, pen, and other extensions in the block category menu in the editor.",
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "settings": [
    {
      "name": "Music",
      "id": "music",
      "type": "boolean",
      "default": false
    },
    {
      "name": "Pen",
      "id": "pen",
      "type": "boolean",
      "default": false
    },
    {
      "name": "Text to Speech",
      "id": "text2speech",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Translate",
      "id": "translate",
      "type": "boolean",
      "default": true
    },
    {
      "name": "App Utilities",
      "id": "appmaker",
      "type": "boolean",
      "default": false
    },
    {
      "name": "Croquet",
      "id": "croquet",
      "type": "boolean",
      "default": false
    },
    {
      "name": "ChatGPT2Scratch",
      "id": "chatgpt2scratch",
      "type": "boolean",
      "default": false
    },
    {
      "name": "ML2Scratch",
      "id": "ml2scratch",
      "type": "boolean",
      "default": false
    },
    {
      "name": "TM2Scratch",
      "id": "tm2scratch",
      "type": "boolean",
      "default": false
    },
    {
      "name": "TMPose2Scratch",
      "id": "tmpose2scratch",
      "type": "boolean",
      "default": false
    },
    {
      "name": "HandPose2Scratch",
      "id": "handpose2scratch",
      "type": "boolean",
      "default": false
    },
    {
      "name": "PoseNet2Scratch",
      "id": "posenet2scratch",
      "type": "boolean",
      "default": false
    },
    {
      "name": "FaceMesh2Scratch",
      "id": "facemesh2scratch",
      "type": "boolean",
      "default": false
    },
    {
      "name": "ImageClassifer2Scratch",
      "id": "ic2scratch",
      "type": "boolean",
      "default": false
    },
    {
      "name": "Scratch2WebSerialAPI",
      "id": "scratch2webserialapi",
      "type": "boolean",
      "default": false
    },
    {
      "name": "TurboWarp",
      "id": "tw",
      "type": "boolean",
      "default": false
    }

  ],
  "dynamicDisable": true,
  "tags": []
};
export default manifest;
